spring.application.name=WebFastFood


# Database configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=WebFastFood;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=12345

# Driver class
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
