spring.application.name=WebFastFood
# URL kết nối: thay 'WebFastFoodDB' bằng tên Database bạn đã tạo trong SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=WebFastFoodDB;encrypt=true;trustServerCertificate=true;

# Tài khoản SQL Server (thường là sa)
spring.datasource.username=sa
spring.datasource.password=123456

# Driver class
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect